[dev]
# On crée un alias "serveur_dev" qui pointe vers la machine locale
serveur_dev ansible_connection=local

[dev:vars]
app_name="Application DEV"
env="dev"
author="Etudiant DEV"

[prod]
# On crée un alias "serveur_prod" qui pointe vers la machine locale
serveur_prod ansible_connection=local

[prod:vars]
app_name="Application PROD"
env="prod"
author="Equipe Ops"